import { FaceShapeType, HairDensity, HairTexture, Hairstyle, MaintenancePreference, StylePreference } from '../types';

export interface CatalogHairstyle extends Omit<Hairstyle, 'matchScore' | 'matchReasons'> {
  suitableFaceShapes: FaceShapeType[];
  suitableHairTextures: HairTexture[];
  suitableHairDensities: HairDensity[];
  suitableStyles: StylePreference[];
  faceShapeAdvantage: Record<FaceShapeType, string>;
}

export const HAIRSTYLE_CATALOG: CatalogHairstyle[] = [
  {
    id: 'textured-crop',
    name: 'Textured Crop',
    persianName: 'کراپ بافت‌دار (فرنچ کراپ مدرن)',
    description: 'مدلی مدرن و بسیار پرطرفدار با چتری کوتاه به سمت جلو و بافت خرد روی سر. دور سر با فید ملایم کوتاه می‌شود.',
    topLength: '۴ تا ۶ سانتی‌متر',
    sides: 'فید مخروطی ملایم (Low Taper Fade)',
    fringe: 'کوتاه صاف یا بافت‌دار به سمت جلو',
    texture: 'خرد و تکسچر عمیق با پودر یا کلی مات',
    volume: 'متوسط و کنترل‌شده',
    finish: 'مات طبیعی و بدون درخشش مصنوعی',
    maintenance: 'low',
    barberNotes: 'دور سر با شانه ۱.۵ شروع شده و به پوست محو شود. بالای سر با تیغ پیتاژ تکسچر سنگین داده شود.',
    previewColor: '#2563EB',
    suitableFaceShapes: ['oval', 'round', 'square', 'heart'],
    suitableHairTextures: ['straight', 'wavy'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['modern', 'textured', 'trendy'],
    faceShapeAdvantage: {
      oval: 'تناسب بی‌نظیر با فرم بیضی بدون دستکاری زاویه‌های طبیعی صورت',
      round: 'چتری کوتاه و اضلاع تیز به کشیده‌تر دیده شدن گونه‌ها کمک می‌کند',
      square: 'بافت نامنظم بالای سر سختی فک مربعی را ملایم و جذاب‌تر می‌کند',
      heart: 'چتری جلو پیشانی عریض را متعادل کرده و تمرکز را روی فک می‌آورد',
      oblong: 'ارتفاع کم بالای سر مانع از درازتر دیده شدن چهره می‌شود',
      diamond: 'بافت لایه‌ای پیشانی باریک را پُرتر نشان می‌دهد',
    },
  },
  {
    id: 'low-taper-fade',
    name: 'Low Taper Fade with Textured Top',
    persianName: 'لو تیپر فید با بالای بافت‌دار',
    description: 'ترکیب خط شقیقه و گردن فید شده با موهای پرپشت طبیعی در بالا. یکی از تمیزترین و شیک‌ترین استایل‌های روزمره.',
    topLength: '۵ تا ۷ سانتی‌متر',
    sides: 'تیپر ملایم در شقیقه‌ها و خط پشت گردن',
    fringe: 'طبیعی به سمت بالا یا کج ملایم',
    texture: 'مواج طبیعی و نرم',
    volume: 'متوسط به بالا',
    finish: 'نیمه‌مات شاداب',
    maintenance: 'low',
    barberNotes: 'تیپر فقط در نقطه شقیقه و پشت گردن، حفظ ضخامت طبیعی در قسمت بالای گوش.',
    previewColor: '#059669',
    suitableFaceShapes: ['oval', 'square', 'oblong', 'diamond'],
    suitableHairTextures: ['straight', 'wavy', 'curly'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['clean', 'modern', 'classic'],
    faceShapeAdvantage: {
      oval: 'خطوط تمیز تیپر ساختار طبیعی و بدون نقص صورت بیضی را برجسته می‌سازد',
      square: 'فید تمیز شقیقه بدون کاستن از ابهت و زاویه مردانه استخوان فک',
      oblong: 'حفظ حجم در طرفین سر از لاغر و باریک دیده شدن نیم‌رخ جلوگیری می‌کند',
      diamond: 'تعادل عالی با زاویه گونه‌ها بدون باریک کردن شقیقه‌ها',
      round: 'تراکم تمیز کناره‌ها به صورت ورم‌کرده فرم استخوانی‌تری می‌دهد',
      heart: 'تقارن شقیقه را با انحنای چانه به هارمونی ایده‌آل می‌رساند',
    },
  },
  {
    id: 'modern-quiff-mid-fade',
    name: 'Modern Quiff with Mid Fade',
    persianName: 'کوئیف مدرن با مید فید',
    description: 'جلوی مو با حجم و شیب به سمت بالا و عقب حالت داده شده و کناره‌های سر با ارتفاع متوسط محو می‌شوند.',
    topLength: '۷ تا ۹ سانتی‌متر در جلو، کوتاه‌تر به سمت تاج سر',
    sides: 'فید متوسط از شانه ۱ تا ۳',
    fringe: 'هدایت به بالا و زاویه‌دار به عقب',
    texture: 'جداشده با شانه دندانه‌درشت و اسپری نمک دریایی',
    volume: 'حجم بالا و لیفت‌دار',
    finish: 'طبیعی با ایستایی قوی',
    maintenance: 'medium',
    barberNotes: 'ایجاد زاویه شیب‌دار از پیشانی تا تاج سر. خط فید دقیقاً بالای استخوان گیجگاهی تنظیم شود.',
    previewColor: '#D97706',
    suitableFaceShapes: ['round', 'square', 'oval'],
    suitableHairTextures: ['straight', 'wavy'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['modern', 'trendy', 'clean'],
    faceShapeAdvantage: {
      round: 'افزایش ارتفاع در بالا باعث کشیده و لاغرتر به نظر رسیدن صورت گرد می‌شود',
      square: 'ترکیب ارتفاع کوئیف با استخوان محکم فک ساختاری بسیار کاریزماتیک ایجاد می‌کند',
      oval: 'حجم کنترل‌شده بدون بر هم زدن بالانس طولی صورت',
      oblong: 'بهتر است ارتفاع در جلو بیش از حد نباشد تا چهره بلندتر نشود',
      heart: 'حجم در جلو تعادل خوبی با چانه باریک برقرار می‌کند',
      diamond: 'به کشیده‌تر شدن فرم کلی و شکستن خط عریض گونه کمک می‌کند',
    },
  },
  {
    id: 'classic-side-part',
    name: 'Executive Side Part Taper',
    persianName: 'ساید پارت کلاسیک مدیریتی',
    description: 'خط فرق طبیعی با شانه تمیز به پهلو و تراکم مرتب در طرفین. استایلی جنتلمن، حرفه‌ای و همواره معتبر.',
    topLength: '۶ تا ۸ سانتی‌متر',
    sides: 'تراکم مرتب با قیچی و تیپر کوتاه شیک',
    fringe: 'شانه خورده به پهلو و متمایل به عقب',
    texture: 'یکدست و آراسته',
    volume: 'متوسط و ساختاریافته',
    finish: 'نیمه براق یا طبیعی کلاسیک با پوماد بر پایه آب',
    maintenance: 'medium',
    barberNotes: 'مشخص کردن فرق طبیعی سر، فرم‌دهی قیچی روی شانه برای ترنزیشن نرم به طرفین.',
    previewColor: '#4F46E5',
    suitableFaceShapes: ['oval', 'square', 'oblong', 'round'],
    suitableHairTextures: ['straight', 'wavy'],
    suitableHairDensities: ['low', 'medium', 'high'],
    suitableStyles: ['classic', 'clean'],
    faceShapeAdvantage: {
      oval: 'کلاسیک‌ترین ترکیب که بر کمال هندسی صورت‌های بیضی مهر تأیید می‌زند',
      square: 'خط کج فرق سر تقارن بیش از حد مربع را به شکلی اشرافی می‌شکند',
      oblong: 'عرض مناسب در طرفین چهره مانع از دراز دیده شدن استخوان‌بندی می‌شود',
      round: 'خط قطری مو کانون دید را از گونه‌های پر به زاویه چشم تغییر می‌دهد',
      heart: 'هدایت مو به یک سمت پیشانی پهن را خنثی و جمع‌وجور می‌کند',
      diamond: 'آرامش بخشیدن به زوایای تیز چهره با خطوط نرم و منظم',
    },
  },
  {
    id: 'curtain-fringe',
    name: 'Curtain Fringe (Middle Part)',
    persianName: 'کرتن فرنج (کوتاهی پرده‌ای مدرن)',
    description: 'مدلی اروپایی با جریان آزاد موها که از فرق وسط یا وسط-مایل به دو سمت شقیقه‌ها قاب می‌بندد.',
    topLength: '۹ تا ۱۲ سانتی‌متر',
    sides: 'قیچی دور گوش با تیپر مخفی یا شانه بلند',
    fringe: 'بلند تا روی استخوان گونه، تقسیم شده به طرفین',
    texture: 'موج‌دار آزاد و طبیعی',
    volume: 'طبیعی، شناور و پویا',
    finish: 'کاملاً مات و ارگانیک',
    maintenance: 'medium',
    barberNotes: 'لایه‌بندی ملایم به سمت عقب با قیچی اسلایس برای حرکت و افتادگی طبیعی موها.',
    previewColor: '#9333EA',
    suitableFaceShapes: ['oval', 'heart', 'diamond', 'oblong'],
    suitableHairTextures: ['wavy', 'straight'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['trendy', 'modern', 'textured'],
    faceShapeAdvantage: {
      oval: 'قاب بستن دو طرف صورت استخوان‌بندی ایده‌آل را همانند یک نقاشی احاطه می‌کند',
      heart: 'پوشش ملایم گوشه‌های پیشانی و هم‌سطح کردن پهنای پیشانی با چانه باریک',
      diamond: 'نرم کردن خط شکست گونه‌ها با حرکت آزاد دسته‌های مو در طرفین',
      oblong: 'افتادن دسته‌ها در اطراف شقیقه به پرتر نشان دادن عرض صورت کمک می‌کند',
      square: 'انحنای ملایم دسته‌های مو خطوط زاویه‌دار گوشه فک را دلنشین می‌سازد',
      round: 'خطوط عمودی دو طرف مو باعث فشرده شدن پهنای گونه‌ها به نظر می‌رسد',
    },
  },
  {
    id: 'buzz-cut-fade',
    name: 'Clean Buzz Cut with Skin Fade',
    persianName: 'باز کات تمیز با اسکین فید',
    description: 'کوتاهی تمام عیار و بی‌دغدغه با کنتراست شدید بین پوست تمیز دور سر و موی شماره ۲ یا ۳ در بالا.',
    topLength: '۰.۶ تا ۱.۲ سانتی‌متر (شانه ۲ یا ۳)',
    sides: 'اسکین فید زیرو صفر تا تیغ',
    fringe: 'خط پیشانی لیزری و تقارن هندسی (Line-up)',
    texture: 'یکنواخت و پرپشت',
    volume: 'حداقل',
    finish: 'مات یکدست',
    maintenance: 'low',
    barberNotes: 'آنکادر دقیق شقیقه‌ها و پیشانی با تیغ، فید بدون پله از صفر به شماره ۲.',
    previewColor: '#DC2626',
    suitableFaceShapes: ['square', 'oval', 'diamond'],
    suitableHairTextures: ['straight', 'wavy', 'curly', 'coily'],
    suitableHairDensities: ['low', 'medium', 'high'],
    suitableStyles: ['clean', 'classic', 'modern'],
    faceShapeAdvantage: {
      square: 'بهترین انتخاب برای نمایش خط فک قدرتمند، مردانه و زاویه‌دار',
      oval: 'تمرکز صددرصدی روی ویژگی‌های جذاب چشم و لب بدون حاشیه مو',
      diamond: 'نمایش بی‌پرده استخوان گونه برجسته با حداکثر جسارت',
      round: 'با اسکین فید بالا به زاویه‌دار شدن خطوط گردن و شقیقه کمک می‌کند',
      heart: 'سادگی تمام عیار و رهایی از حجم اضافه بالای سر',
      oblong: 'طول بسیار کوتاه مانع از بلندتر به نظر رسیدن صورت می‌شود',
    },
  },
  {
    id: 'tapered-curly-top',
    name: 'Tapered Curls with Crisp Edge',
    persianName: 'فرفری کنترل‌شده با دور تیپر',
    description: 'نمایش زیبایی و بافت طبیعی موهای فر و مجعد در بالا، در حالی که لبه‌ها و خط گردن کاملاً منظم و کنترل شده‌اند.',
    topLength: '۶ تا ۱۰ سانتی‌متر',
    sides: 'لو یا مید تیپر تمیز',
    fringe: 'فرفری نرم روی پیشانی',
    texture: 'حلقه‌ای تعریف‌شده با کرم موی ضد وز',
    volume: 'بالا و فنری',
    finish: 'آبرسانی‌شده و با طراوت',
    maintenance: 'medium',
    barberNotes: 'کات مو در حالت خشک برای دیدن الگوی فرها. پاکسازی تمیز دور گوش و خط ریش.',
    previewColor: '#0284C7',
    suitableFaceShapes: ['oval', 'square', 'heart', 'diamond'],
    suitableHairTextures: ['curly', 'coily', 'wavy'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['textured', 'trendy', 'modern'],
    faceShapeAdvantage: {
      oval: 'بافت پرانرژی فرها به تقارن چهره جان و جذابیت مضاعف می‌بخشد',
      square: 'حلقه‌های مواج خط فک مربعی را تلطیف کرده و هارمونی مدرنی می‌سازد',
      heart: 'بافت در بالای سر زاویه چانه را تراز و نگاه‌ها را به چشمان معطوف می‌کند',
      diamond: 'پوشش بالای شقیقه‌ها باعث تعادل با عرض استخوان گونه می‌شود',
      round: 'تنظیم حجم رو به بالا به کشیده‌تر شدن فرم دایره‌ای کمک می‌کند',
      oblong: 'پراکندگی عرضی فرها به پهنای لاغر صورت بعد اضافه می‌کند',
    },
  },
  {
    id: 'burst-fade-mullet',
    name: 'Modern Textured Mullet / Burst Fade',
    persianName: 'مید فید با مولت بافت‌دار مدرن',
    description: 'استایل جسورانه و ترند نسل جوان با فید هلالی دور گوش و طول بیشتر در تاج و پشت گردن.',
    topLength: '۶ تا ۸ سانتی‌متر بالا، ۸ تا ۱۰ سانتی‌متر پشت',
    sides: 'برست فید نیم‌دایره اطراف گوش',
    fringe: 'کراپ یا چتری بافت‌دار کوتاه',
    texture: 'مات اسپایک و پر از حرکت',
    volume: 'متوسط رو به بالا',
    finish: 'مات پر بافت',
    maintenance: 'high',
    barberNotes: 'برست فید متقارن دور گوش، حفظ لایه‌های پشت سر با تکسچر پر.',
    previewColor: '#E11D48',
    suitableFaceShapes: ['oval', 'oblong', 'diamond'],
    suitableHairTextures: ['wavy', 'straight', 'curly'],
    suitableHairDensities: ['medium', 'high'],
    suitableStyles: ['trendy', 'textured'],
    faceShapeAdvantage: {
      oval: 'استایلی پر انرژی و پیشرو برای صورت‌های متقارن',
      oblong: 'پوشش پشت گردن و پهلوها زاویه گردن را کوتاه‌تر و پرتر نشان می‌دهد',
      diamond: 'فید هلالی پشت شقیقه نگاه‌ها را از برجستگی گونه‌ها تعدیل می‌کند',
      square: 'کنتراست بالای مو با زاویه فک استایلی بسیار خاص ایجاد می‌کند',
      round: 'حرکت خطوط فید به صورت‌های گرد کشیدگی بصری می‌بخشد',
      heart: 'تعادل بین حجم پشت گردن و باریکی چانه در نمای نیم‌رخ',
    },
  },
];
