export enum DomainErrorCode {
  // Booking & Slots
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_CANCELLED = 'BOOKING_ALREADY_CANCELLED',
  BOOKING_ALREADY_COMPLETED = 'BOOKING_ALREADY_COMPLETED',
  BOOKING_CANNOT_BE_CANCELLED = 'BOOKING_CANNOT_BE_CANCELLED',
  INVALID_BOOKING_TRANSITION = 'INVALID_BOOKING_TRANSITION',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  PAST_DATE_NOT_ALLOWED = 'PAST_DATE_NOT_ALLOWED',

  // Payment
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_VERIFIED = 'PAYMENT_ALREADY_VERIFIED',
  INVALID_PAYMENT_TRANSITION = 'INVALID_PAYMENT_TRANSITION',
  PAYMENT_PROOF_REQUIRED = 'PAYMENT_PROOF_REQUIRED',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Catalog & Staff & Customer
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_INACTIVE = 'SERVICE_INACTIVE',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_INACTIVE = 'STAFF_INACTIVE',
  STAFF_DOES_NOT_PROVIDE_SERVICE = 'STAFF_DOES_NOT_PROVIDE_SERVICE',
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Multi-Tenancy & Auth
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_SUSPENDED = 'ORGANIZATION_SUSPENDED',
  UNAUTHORIZED_TENANT_ACCESS = 'UNAUTHORIZED_TENANT_ACCESS',
  FORBIDDEN_PERMISSION = 'FORBIDDEN_PERMISSION',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  CONCURRENCY_CONFLICT = 'CONCURRENCY_CONFLICT',
}

export class DomainError extends Error {
  public readonly code: DomainErrorCode;
  public readonly details?: Record<string, unknown>;

  constructor(code: DomainErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
    this.details = details;
    Object.setPrototypeOf(this, DomainError.prototype);
  }
}
